### ISSUE TITLE
Search bar is not present on address page on mobile

### ISSUE THREAD

**Issue by karynemayer** [telosnetwork/teloscan#260]
## Overview

When using mobile, you don't see the search bar on the address page.

## Steps to reproduce

Use you phone or a mobile size screen to test it.

1. Go to teloscan
2. Identify that there is no search bar

## Current behavior

There is no searchbar
## Expected behavior

Searchbar should be available

**Comment by EJSG** [comment]
note for future grooming, this should probably be considered part of a general header refactor. search bar needs to have the highest affordance other than burger menu. light/dark theme toggle should be in the dropdown menu to make room for search, and for unsupported browsers (ie. mobile outside of metamask app built-in browser) we should not show the "Connect Wallet" button at all, as it is broken due to universal lack of mobile browser addons.

**Comment by karynemayer** [comment]
Will be addressed in https://github.com/telosnetwork/teloscan/issues/274
