### ISSUE TITLE
WTLOS balance incorrect after withdrawal (unwrap)

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#709]
**Describe the bug**

When an address withdraws (unwraps) WTLOS, the balance of TLOS is not updated on Teloscan. Additionally, the ERC20 transfer field is empty for the withdrawal transaction, even though it should contain the relevant information.

**To Reproduce**

1. Go to [this withdrawal transaction page](https://testnet.teloscan.io/tx/0xd895be51306468d9bbb920bd635fff2fff7e5ae73fcf2eafac108b43a1577e9c).

2. Note that the ERC20 transfer field is empty:
  
<img width="986" alt="image" src="https://github.com/telosnetwork/teloscan/assets/97489909/3a41a17c-f764-4965-bacb-d06c14e53eba">

3. Click on the address and go to [this page](https://testnet.teloscan.io/address/0x1Da699A4fCCdD5Fb02562767C54b720DeC79212f?tab=tokens) to view the address balances. Note the incorrect TLOS balance.

4. Verify the user's WTLOS balance on the [WTLOS contract page](https://testnet.teloscan.io/address/0xaE85Bf723A9e74d6c663dd226996AC1b8d075AA9?tab=contract). Go to the "Read" tab, use the "balanceOf" method, and enter the address `0x1Da699A4fCCdD5Fb02562767C54b720DeC79212f`. The balance should be `2000000000000000000`.

**Expected behavior**

- The ERC20 transfer field should contain the relevant information for the WTLOS withdrawal transaction.
- The TLOS balance of the address should be updated on Teloscan after the withdrawal transaction.

**Actual behavior**

- The ERC20 transfer field is empty for the WTLOS withdrawal transaction.
- The TLOS balance of the address is not updated on Teloscan after the withdrawal transaction.

**Screenshots**
 ERC20 transfer field is empty:
  
<img width="986" alt="image" src="https://github.com/telosnetwork/teloscan/assets/97489909/3a41a17c-f764-4965-bacb-d06c14e53eba">

**Comment by Viterbo** [comment]
There's a problem with this requirement:
![image](https://github.com/telosnetwork/teloscan/assets/4420760/f4e10d82-1e39-42ed-8cdd-e574c2f9ec37)

In the withdrawal action, there's no ERC20 transfer at all. So, this is not a bug that that field shows empty. The bug instead is showing the field name when it's empty (but that issue is tracked in #700)
![image](https://github.com/telosnetwork/teloscan/assets/4420760/1b73945a-ed6f-4c93-8fe1-71d35705b143)
![image](https://github.com/telosnetwork/teloscan/assets/4420760/ee55593a-63db-4d55-9ed5-d90d46f35ef5)
![image](https://github.com/telosnetwork/teloscan/assets/4420760/59e08a03-b07a-42c7-bb95-9c6e3ebf41b7)

**Comment by Viterbo** [comment]
https://etherscan.io/tx/0xad065a940f49efb4aca641ddcf4ca208ad54b2ffb21c43741fde5e94fcc48491

**Comment by pmjanus** [comment]
We want instead to add a transaction action field that states 

Transaction Action:

Unwrap 0.2438 ￼ WTLOS into 0.2438TLOS
