### ISSUE TITLE
Invalid Age on Transactions Table for an Address

### ISSUE THREAD

**Issue by pmjanus** [telosnetwork/teloscan#737]
<img width="1370" alt="image" src="https://github.com/telosnetwork/teloscan/assets/97489909/b95786ee-a654-4377-b04b-92b958a79c96">
https://www.teloscan.io/address/0xA0fB8cd450c8Fd3a11901876cD5f17eB47C6bc50

1. Go to address, view table, the age column gives NaN days ago, it should return a valid date format such as 2 hours ago.
2. Note: the block for the transaction gives the correct timestamp.

**Comment by Viterbo** [comment]
The problem is that we previously received the timestamp parameter as a **number** representing milliseconds (epoch time), and now we receive a **string** with the date in the standard ISO format.

![image](https://github.com/telosnetwork/teloscan/assets/4420760/0b2ecd7e-50e3-495b-bdda-f16689523ef8)
