### ISSUE TITLE
Stop downloading NFT preview image on click

### ISSUE THREAD

**Issue by rozzaswap** [telosnetwork/teloscan#740]
See https://github.com/telosnetwork/teloscan/issues/670

--------
addressed in this PR: https://github.com/telosnetwork/teloscan/pull/745

**Comment by Viterbo** [comment]
The problem is this line:
https://github.com/telosnetwork/teloscan/blob/dev/src/components/Token/NFTList.vue#L340

What happens is that these particular NFTs have embedded image data instead of an URL. So we can't show it in a new tab.

The solution suggested: pop up a sign to confirm or deny the image download.
